import { Category, CategoryConfig } from './types'

export const CATEGORY_CONFIG: Record<Category, CategoryConfig> = {
  COLLEGE: {
    label: 'Colleges',
    icon: '🏫',
    desc: 'Ask your query related to admissions, fees, placements, cutoffs etc',
    subTabs: ['All', 'Admissions', 'Fees', 'Facility', 'Placements'],
    samples: [
      'How can I get admission to VIT Vellore?',
      'How much is the fee at DTU?',
      'What are the hostel facilities like at IIT Bombay?',
      'Which companies visited LPU for placements this year?',
      'What need-based scholarships are available at Amity University?',
    ],
    subTabSamples: {
      'All': [
        'How can I get admission to VIT Vellore?',
        'How much is the fee at DTU?',
        'What are the hostel facilities like at IIT Bombay?',
        'Which companies visited LPU for placements this year?',
        'What need-based scholarships are available at Amity University?',
      ],
      'Admissions': [
        'What is the admission process for SRM University?',
        'What is the minimum JEE score required for NIT Trichy?',
        'Does Manipal University accept KCET scores for admission?',
        'What documents are needed for admission to Amity University?',
        'Is there a management quota at VIT Vellore?',
      ],
      'Fees': [
        'What is the total 4-year fee at VIT Vellore?',
        'How much is the annual fee at BITS Pilani?',
        'What is the hostel fee at Chandigarh University?',
        'Are there any hidden charges at LPU beyond tuition?',
        'What is the fee structure for B.Tech at Amrita University?',
      ],
      'Facility': [
        'Does LPU have a good sports complex?',
        'What are the library facilities at IIT Madras?',
        'How is the Wi-Fi and internet connectivity at VIT Vellore?',
        'Does Manipal University have a hospital for medical students?',
        'What lab facilities are available at NIT Warangal?',
      ],
      'Placements': [
        'What is the average package at BITS Pilani?',
        'Which top companies recruit from NIT Trichy?',
        'How is the placement record of Amrita University for CSE?',
        'What is the highest package offered at VIT Vellore?',
        'Does SRM University have good placement support for core branches?',
      ],
    },
  },
  EXAM: {
    label: 'Exams',
    icon: '📝',
    desc: 'Get answers on dates, syllabus, prep tips etc',
    subTabs: ['All', 'Admit Card', 'Mock Test', 'Results', 'Dates'],
    samples: [
      'What is the exam pattern for JEE Main?',
      'Where can I download MHT CET admit card?',
      'Where can I download TS EAMCET sample papers?',
      'Who is the highest scorer in AP EAMCET this year?',
      'When will the application for JEE Advanced begin?',
    ],
    subTabSamples: {
      'All': [
        'What is the exam pattern for JEE Main?',
        'Where can I download MHT CET admit card?',
        'Where can I download TS EAMCET sample papers?',
        'Who is the highest scorer in AP EAMCET this year?',
        'When will the application for JEE Advanced begin?',
      ],
      'Admit Card': [
        'How do I download my JEE Main 2025 admit card?',
        'When will the NEET 2025 hall ticket be released?',
        'Where can I get my GATE 2025 admit card?',
        'What details are printed on the MHT CET admit card?',
        'What should I do if my name is wrong on the CLAT admit card?',
      ],
      'Mock Test': [
        'Where can I find free JEE Main mock tests online?',
        'Are there official NEET mock tests on the NTA website?',
        'How many mock tests should I attempt before GATE?',
        'Where can I download TS EAMCET previous year papers?',
        'What is the best strategy for attempting BITSAT mock tests?',
      ],
      'Results': [
        'When will JEE Main Session 2 results be declared?',
        'How can I check my NEET 2025 scorecard?',
        'Where is the GATE 2025 result published?',
        'How is the MHT CET percentile calculated?',
        'What is the cutoff score to qualify CLAT 2025?',
      ],
      'Dates': [
        'What is the JEE Advanced 2025 exam date?',
        'When does the NEET 2025 application form open?',
        'What are the important dates for GATE 2026?',
        'When is the CLAT 2026 exam scheduled?',
        'What is the last date to apply for MHT CET 2025?',
      ],
    },
  },
  COMPARISON: {
    label: 'Comparisons',
    icon: '⚖️',
    desc: 'Compare colleges and courses',
    subTabs: ['All', 'Compare Colleges'],
    samples: [
      'Which has better placements, VIT Vellore or Amrita School of Engineering?',
      'Which college offers a better sports facility, DTU or Amity?',
      'How do campus facilities compare between IIT Bombay and IIT Delhi?',
      'Which college has a better NIRF ranking, LPU or Chandigarh University?',
      'What is the fee difference between College of Engineering and VIT Pune?',
    ],
    subTabSamples: {
      'All': [
        'Which has better placements, VIT Vellore or Amrita School of Engineering?',
        'Which college offers a better sports facility, DTU or Amity?',
        'How do campus facilities compare between IIT Bombay and IIT Delhi?',
        'Which college has a better NIRF ranking, LPU or Chandigarh University?',
        'What is the fee difference between College of Engineering and VIT Pune?',
      ],
      'Compare Colleges': [
        'Compare BITS Pilani vs NIT Trichy for Computer Science',
        'Which is better for MBA, IIM Indore or IIM Kozhikode?',
        'Compare Manipal University vs SRM University on fees and placements',
        'Which has a better campus, Amity Noida or Amity Gurugram?',
        'Compare VIT Chennai vs VIT Vellore — which is better?',
      ],
    },
  },
  PREDICTOR: {
    label: 'Predictors',
    icon: '🔮',
    desc: 'Predict colleges based on rank, scores, percentiles',
    subTabs: ['All', 'College Predictor', 'Admission Chances'],
    samples: [
      'Which colleges accept 70 rank in JEE Main?',
      'What is the entrance exam cutoff for VIT Vellore this year?',
      'What are the best colleges for 70 percentile in MHT CET?',
      'Cutoffs for all branches at DTU?',
      'Can I get into top colleges with 70 rank in TS EAMCET?',
    ],
    subTabSamples: {
      'All': [
        'Which colleges accept 70 rank in JEE Main?',
        'What is the entrance exam cutoff for VIT Vellore this year?',
        'What are the best colleges for 70 percentile in MHT CET?',
        'Cutoffs for all branches at DTU?',
        'Can I get into top colleges with 70 rank in TS EAMCET?',
      ],
      'College Predictor': [
        'Which NITs can I get with JEE Main rank 15000?',
        'What colleges are available for 85 percentile in MHT CET?',
        'Which private colleges accept AP EAMCET rank 5000?',
        'What are my options with GATE score 650 for M.Tech?',
        'Which IIITs can I get with JEE Main rank 8000?',
      ],
      'Admission Chances': [
        'What are my chances of getting CSE at NIT Warangal with rank 3000?',
        'Can I get Mechanical at BITS Pilani with 280 score?',
        'Is 95 percentile in MHT CET enough for COEP Pune?',
        'What branch can I get at DTU with JEE Main rank 12000?',
        'Can I get into VIT Vellore with 90 percentile in JEE Main?',
      ],
    },
  },
  TOP_COLLEGES: {
    label: 'Top Colleges',
    icon: '🏆',
    desc: 'Explore colleges by location, ranking',
    subTabs: ['All', 'Colleges by Location', 'Top Ranked Colleges'],
    samples: [
      'B.E. / B.Tech colleges in India',
      'Top Ranked B.E. / B.Tech colleges in Mumbai',
      'Private B.E. / B.Tech colleges in Bangalore',
      'Which are the Top Ranked B.E. / B.Tech colleges in Jaipur?',
      'Popular B.E. / B.Tech colleges in Kolkata',
    ],
    subTabSamples: {
      'All': [
        'Best B.Tech colleges in India by NIRF ranking',
        'Top engineering colleges in Maharashtra',
        'Best private universities in South India',
        'Top colleges for Computer Science in India',
        'Which are the top deemed universities in India?',
      ],
      'Colleges by Location': [
        'Top engineering colleges in Pune',
        'Best B.Tech colleges in Hyderabad',
        'Top private colleges in Chennai',
        'Best engineering colleges in Delhi NCR',
        'Top colleges for B.Tech in Bangalore',
      ],
      'Top Ranked Colleges': [
        'Top 10 engineering colleges in India by NIRF 2024',
        'Best government engineering colleges in India',
        'Top ranked private universities in India',
        'Which colleges are in the top 50 NIRF engineering ranking?',
        'Best colleges for B.Tech CSE in India by placement record',
      ],
    },
  },
}

export const API_BASE = '/api'
